- src/main/java/com/ss/hanarowa/facility/entity/FacilityTime.java
- src/main/java/com/ss/hanarowa/lesson/entity/Category.java
- src/main/java/com/ss/hanarowa/member/entity/Advice.java
- src/main/java/com/ss/hanarowa/member/entity/Category.java
- src/main/java/com/ss/hanarowa/member/entity/Member.java
- src/main/java/com/ss/hanarowa/member/entity/MyLesson.java
- src/main/java/com/ss/hanarowa/member/entity/Review.java
> Feat: right-entity 작업 완료

- build.gradle
- src/main/java/com/ss/hanarowa/config/CustomSecurityConfig.java
- src/main/java/com/ss/hanarowa/config/SwaggerConfig.java
- src/main/java/com/ss/hanarowa/member/dto/MemberDTO.java
- src/main/java/com/ss/hanarowa/security/JwtAuthenticationFilter.java
- src/main/java/com/ss/hanarowa/security/JwtUtil.java
- src/main/java/com/ss/hanarowa/security/exception/CustomJwtException.java
- src/main/java/com/ss/hanarowa/security/handler/CustomAccessDeiniedHandler.java
- src/main/java/com/ss/hanarowa/security/handler/LoginFailureHandler.java
- src/main/java/com/ss/hanarowa/security/handler/LoginSuccessHandler.java
> Feat: config 추가

- src/main/java/com/ss/hanarowa/config/CustomSecurityConfig.java
- src/main/java/com/ss/hanarowa/member/dto/MemberRegistDTO.java
- src/main/java/com/ss/hanarowa/member/entity/Member.java
- src/main/java/com/ss/hanarowa/member/repository/MemberRepository.java
- src/main/java/com/ss/hanarowa/member/service/MemberService.java
- src/main/java/com/ss/hanarowa/member/service/impl/MemberServiceImpl.java
- src/main/java/com/ss/hanarowa/security/JwtUtil.java
> Feat: config 수정

- src/main/java/com/ss/hanarowa/member/entity/Member.java
- src/main/java/com/ss/hanarowa/member/entity/MyLesson.java
member 엔티티 칼럼 2개 추가(provider 관련)
> fix:member entity 수정

- src/main/java/com/ss/hanarowa/member/controller/MemberController.java
- src/main/java/com/ss/hanarowa/member/dto/MemberInfoDTO.java
- src/main/java/com/ss/hanarowa/member/dto/MemberRegistDTO.java
- src/main/java/com/ss/hanarowa/member/repository/MemberRepository.java
- src/main/java/com/ss/hanarowa/member/service/MemberService.java
- src/main/java/com/ss/hanarowa/member/service/impl/MemberServiceImpl.java
- src/main/java/com/ss/hanarowa/security/JwtAuthenticationFilter.java
- src/test/java/com/ss/hanarowa/member/repository/MemberRepositoryTest.java
- src/test/java/com/ss/hanarowa/repository/MemberRepositoryTest.java
- src/test/java/com/ss/hanarowa/repository/RepositoryTest.java
회원가입과 MemberRepositoryTest 만들었어요
> Feat: 회원가입 구현

- src/main/java/com/ss/hanarowa/domain/lesson/repository/RoomTimeRepository.java
- src/main/java/com/ss/hanarowa/domain/member/repository/MyLessonRepository.java
> fix: repository 잘못된 entitiy 이름 변경

- src/main/java/com/ss/hanarowa/domain/facility/controller/FacilityController.java
- src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
- src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
- src/main/java/com/ss/hanarowa/domain/member/entity/Member.java
- src/main/java/com/ss/hanarowa/domain/member/service/MemberService.java
- src/main/java/com/ss/hanarowa/domain/member/service/impl/MemberServiceImpl.java
회원탈퇴 구현 완료
Member 엔티티의 deltedAt 타입 LocalDate -> LocalDateTime 으로 변경했습니다
> Feat:회원탈퇴 구현

- src/main/java/com/ss/hanarowa/domain/lesson/controller/AdminController.java
- src/main/java/com/ss/hanarowa/domain/member/dto/MemberAuthDTO.java
- src/main/java/com/ss/hanarowa/global/security/JwtAuthenticationFilter.java
> Fix: AdminLesson

- src/main/java/com/ss/hanarowa/domain/facility/controller/FacilityController.java
- src/main/java/com/ss/hanarowa/domain/lesson/controller/AdminController.java
- src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
- src/main/java/com/ss/hanarowa/domain/member/dto/MemberInfoDTO.java
- src/main/java/com/ss/hanarowa/domain/member/service/MemberService.java
- src/main/java/com/ss/hanarowa/domain/member/service/impl/MemberServiceImpl.java
- src/main/java/com/ss/hanarowa/global/util/Format.java
회원정보 수정(생년월일, 전화번호) 기능 구현했습니다.
MemberInfoDTO의 LocalDate 타입이었던 birth 를 String 으로 변경하고, util 패키지 밑 Format 클래스를 만들어 String 을 LocalDate 로 변경하는 함수를 작성했습니다.
> Feat: member modify

- src/main/java/com/ss/hanarowa/domain/facility/controller/FacilityController.java
- src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
- src/main/java/com/ss/hanarowa/domain/member/dto/MemberRegistDTO.java
비밀번호 validation 수정, swagger 로그인 초기값 설정
> Feat: 로그인 자동완성, 비밀번호 특수문자 제거

- src/main/java/com/ss/hanarowa/domain/branch/controller/BranchController.java
- src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
- src/main/java/com/ss/hanarowa/domain/member/service/MemberService.java
- src/main/java/com/ss/hanarowa/domain/member/service/impl/MemberServiceImpl.java
- src/main/java/com/ss/hanarowa/global/exception/ExceptionAdvice.java
- src/main/java/com/ss/hanarowa/global/response/code/status/ErrorStatus.java
branch 선택/수정& GeneralException 처리
> Feat: branch 선택/수정& GeneralException 처리

- src/main/java/com/ss/hanarowa/global/config/CustomSecurityConfig.java
- src/main/java/com/ss/hanarowa/global/security/JwtAuthenticationFilter.java
- src/main/java/com/ss/hanarowa/global/security/handler/CustomAccessDeiniedHandler.java
> fix: 로그인 쓸데없는 코드 제거 및 정리

- src/main/java/com/ss/hanarowa/domain/member/controller/AdminMemberController.java
- src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
- src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
- src/main/java/com/ss/hanarowa/domain/member/dto/request/LoginRequestDTO.java
- src/main/java/com/ss/hanarowa/domain/member/dto/request/ModifyPasswdRequestDTO.java
- src/main/java/com/ss/hanarowa/domain/member/dto/response/MemberListResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/member/repository/MemberRepository.java
- src/main/java/com/ss/hanarowa/domain/member/service/AdminMemberService.java
- src/main/java/com/ss/hanarowa/domain/member/service/MemberService.java
- src/main/java/com/ss/hanarowa/domain/member/service/impl/AdminMemberServiceImpl.java
- src/main/java/com/ss/hanarowa/domain/member/service/impl/MemberServiceImpl.java
관리자의 회원 목록 조회 기능 구현했습니다.
AdminController -> AdminMemberController 이런식으로 명명해야 합니다! (클래스 이름 중복)
> Feat: 관리자 회원목록

- src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonListSearchResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/repository/LessonRepository.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
강좌&강사명 강좌 목록 검색 API 구현 완료했습니다.
> Feat: 강좌&강사명 강좌 목록 검색 API 구현

- src/main/java/com/ss/hanarowa/domain/facility/controller/AdminFacilityController.java
- src/main/java/com/ss/hanarowa/domain/facility/controller/FacilityController.java
- src/main/java/com/ss/hanarowa/domain/facility/dto/reponse/AdminFacilityResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/facility/repository/FacilityTimeRepository.java
- src/main/java/com/ss/hanarowa/domain/facility/service/FacilityService.java
- src/main/java/com/ss/hanarowa/domain/facility/service/impl/FacilityServiceImpl.java
> Feat: 관리자 시설 예약 내역 조회 API

- .github/workflows/cicd.yml
> Fix:cicd.yml

- .github/workflows/cicd.yml
> fix: yml v-2

- .github/workflows/cicd.yml
> fix: yml v-5

- .github/workflows/cicd.yml
- .gitignore
- src/main/resources/application.properties
최종 applicationproperties 수정했습니다.
> Feat: SecretApplicationproperties

- src/main/java/com/ss/hanarowa/domain/branch/entity/Branch.java
- src/main/java/com/ss/hanarowa/domain/branch/entity/Location.java
- src/main/java/com/ss/hanarowa/domain/facility/entity/Facility.java
- src/main/java/com/ss/hanarowa/domain/lesson/entity/LessonGisu.java
- src/main/java/com/ss/hanarowa/domain/lesson/entity/LessonRoom.java
- src/main/java/com/ss/hanarowa/domain/lesson/entity/RoomTime.java
Entity 의 Id 가 long 인 애들 Long 으로 바꿨습니다. 이렇게 안하면 나중에 RepoTest 에서 에러납니다...
> Fix: id 타입 long -> Long

- build.gradle
- src/test/java/com/ss/hanarowa/repository/MyLessonRepositoryTest.java
MyLessonRepositoryTest 코드 생성했습니다
> Feat:MyLessonRepositoryTest 생성

- dump.sql
- src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
- src/main/java/com/ss/hanarowa/domain/member/controller/JwtRefreshController.java
- src/main/java/com/ss/hanarowa/domain/member/dto/request/LoginRequestDTO.java
- src/main/java/com/ss/hanarowa/domain/member/dto/response/LoginResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/member/service/MemberService.java
- src/main/java/com/ss/hanarowa/domain/member/service/impl/MemberServiceImpl.java
- src/main/java/com/ss/hanarowa/global/config/CustomSecurityConfig.java
- src/main/java/com/ss/hanarowa/global/response/code/status/ErrorStatus.java
- src/main/java/com/ss/hanarowa/global/security/JwtAuthenticationFilter.java
- src/main/java/com/ss/hanarowa/global/security/handler/LoginSuccessHandler.java
- src/main/java/com/ss/hanarowa/global/security/handler/OAuth2SuccessHandler.java
> Fix : 로그인 dto 수정

- src/test/java/com/ss/hanarowa/domain/lesson/repository/LessonRepositoryTest.java
- src/test/java/com/ss/hanarowa/domain/lesson/repository/LessonRoomRepositoryTest.java
> Feat:LessonRoom 엔티티 CRUD 테스트 코드 생성

- src/test/java/com/ss/hanarowa/domain/lesson/repository/LessonRepositoryTest.java
> Feat:Lesson 엔티티 CRUD 테스트 코드 생성

- src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/request/CreateLessonRequestDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
- src/main/java/com/ss/hanarowa/global/response/code/status/ErrorStatus.java
> Feat: 강좌 개설 신청하기

- src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
- src/main/java/com/ss/hanarowa/domain/member/controller/JwtRefreshController.java
- src/main/java/com/ss/hanarowa/global/security/CustomOAuth2UserService.java
- src/main/java/com/ss/hanarowa/global/security/handler/OAuth2SuccessHandler.java
> Refactor: refresh 토큰 쿠키에 저장

- src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
- src/main/java/com/ss/hanarowa/domain/member/dto/request/ModifyPasswdRequestDTO.java
> Feat:비밀번호 변경 API 구현

- src/main/java/com/ss/hanarowa/domain/facility/controller/FacilityController.java
- src/main/java/com/ss/hanarowa/domain/facility/dto/reponse/FacilityReservationResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/facility/service/FacilityService.java
- src/main/java/com/ss/hanarowa/domain/facility/service/impl/FacilityServiceImpl.java
- src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
> Fix: 강좌,시설예약 api 수정

- src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/response/MyOpenLessonListResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/response/OfferedLessonListResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/entity/Lesson.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
- src/main/java/com/ss/hanarowa/domain/member/entity/MyLesson.java
> Fix: 내 개설강의, 예약강의 response 수정

- src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
- src/main/java/com/ss/hanarowa/domain/member/dto/request/MemberRegistRequestDTO.java
- src/main/java/com/ss/hanarowa/domain/member/dto/request/ModifyPasswdRequestDTO.java
- src/main/java/com/ss/hanarowa/domain/member/dto/response/MemberInfoResponseDTO.java
회원정보 수정 관련한 DTO 들 Pattern 수정했습니다.
> Fix: 회원 정보 수정 관련 DTO 수정

- src/main/java/com/ss/hanarowa/domain/member/controller/JwtRefreshController.java
- src/main/java/com/ss/hanarowa/global/security/JwtAuthenticationFilter.java
- src/main/java/com/ss/hanarowa/global/security/JwtUtil.java
> Fix: refresh 토큰 갱신 에러 수정

- src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/request/TimeAvailabilityRequestDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/response/TimeAvailabilityResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/repository/LessonRoomRepository.java
- src/main/java/com/ss/hanarowa/domain/lesson/repository/RoomTimeRepository.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/LessonService.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
- src/main/java/com/ss/hanarowa/global/response/code/status/ErrorStatus.java
> Feat:Lesson Room

- src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
- src/main/java/com/ss/hanarowa/domain/member/service/AdminMemberService.java
- src/main/java/com/ss/hanarowa/global/config/CustomSecurityConfig.java
- src/main/java/com/ss/hanarowa/global/security/JwtAuthenticationFilter.java
- src/main/java/com/ss/hanarowa/global/security/handler/CustomAccessDeniedHandler.java
관리자 회원목록 API 연동 및 controller 조금 수정했습니다
> Feat:관리자 회원목록 API 연동

- src/main/java/com/ss/hanarowa/domain/lesson/controller/LessonController.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/request/MyReservationPageResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonListResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/response/MyOpenLessonListResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/repository/ReviewRepository.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
> Fix : 시설예약 api

- src/main/java/com/ss/hanarowa/domain/facility/controller/AdminFacilityController.java
- src/main/java/com/ss/hanarowa/domain/facility/dto/reponse/AdminFacilityResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/facility/service/impl/FacilityServiceImpl.java
> Feat:관리자 시설 목록 조회 API 및 관련 DTO 수정 + 날짜 함수 추가

- src/main/java/com/ss/hanarowa/domain/facility/dto/reponse/AdminFacilityResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/facility/service/impl/FacilityServiceImpl.java
> Feat:관리자 시설 예약목록 API DTO 수정

- src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
- src/main/java/com/ss/hanarowa/domain/member/service/MemberService.java
- src/main/java/com/ss/hanarowa/domain/member/service/impl/MemberServiceImpl.java
자신의 지점을 조회하는 api 추가했습니다.
`/member/branch`
> Feat: 자신의 지점을 조회하는 api 

- src/main/java/com/ss/hanarowa/domain/ai/controller/AIController.java
- src/main/java/com/ss/hanarowa/domain/branch/controller/BranchController.java
- src/main/java/com/ss/hanarowa/domain/facility/controller/AdminFacilityController.java
- src/main/java/com/ss/hanarowa/domain/facility/controller/FacilityController.java
- src/main/java/com/ss/hanarowa/domain/facility/dto/reponse/AdminFacilityResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/facility/dto/reponse/FacilityDetailResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/facility/dto/reponse/FacilityReservationResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/facility/dto/request/FacilityReservationDTO.java
- src/main/java/com/ss/hanarowa/domain/facility/entity/FacilityTime.java
- src/main/java/com/ss/hanarowa/domain/facility/service/AdminFacilityService.java
- src/main/java/com/ss/hanarowa/domain/facility/service/FacilityService.java
- src/main/java/com/ss/hanarowa/domain/facility/service/impl/AdminFacilityServiceImpl.java
- src/main/java/com/ss/hanarowa/domain/facility/service/impl/FacilityServiceImpl.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonListByBranchIdResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonListResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonListSearchResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/response/OfferedLessonListResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/entity/Curriculum.java
- src/main/java/com/ss/hanarowa/domain/lesson/entity/RoomTime.java
- src/main/java/com/ss/hanarowa/domain/lesson/repository/ReviewRepository.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/impl/AdminLessonServiceImpl.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/impl/ReviewServiceImpl.java
- src/main/java/com/ss/hanarowa/domain/member/dto/request/LoginRequestDTO.java
- src/main/java/com/ss/hanarowa/domain/member/dto/request/MemberRegistRequestDTO.java
- src/main/java/com/ss/hanarowa/domain/member/dto/response/MemberListResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/member/entity/Advice.java
- src/main/java/com/ss/hanarowa/global/util/Format.java
불필요한 주석들 제거하고 Format 에 static 함수들 몇 가지 추가했습니다
> Refactor: 불필요 주석 제거 및 Format static 함수 추가

- src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
- src/main/java/com/ss/hanarowa/domain/member/service/impl/MemberServiceImpl.java
> Fix: 회원가입시 바로 로그인

- src/main/java/com/ss/hanarowa/domain/lesson/controller/AdminLessonController.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/request/CreateLessonRequestDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/request/UpdateLessonGisuRequestDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/dto/response/LessonGisuDetailResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/AdminLessonService.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/impl/AdminLessonServiceImpl.java
- src/main/java/com/ss/hanarowa/domain/lesson/service/impl/LessonServiceImpl.java
> Fix: Create lesson request dto

- src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
- src/main/java/com/ss/hanarowa/domain/member/controller/JwtRefreshController.java
- src/main/java/com/ss/hanarowa/domain/member/controller/MemberController.java
- src/main/java/com/ss/hanarowa/domain/member/dto/response/MemberInfoResponseDTO.java
- src/main/java/com/ss/hanarowa/global/security/CustomAuthenticationEntryPoint.java
- src/main/java/com/ss/hanarowa/global/security/handler/CustomSuccessHandler.java
> Fix: token로직 전반적인 수정

- src/main/java/com/ss/hanarowa/domain/member/controller/AuthController.java
> Fix: properties

- src/main/java/com/ss/hanarowa/domain/member/controller/AdminMemberController.java
- src/main/java/com/ss/hanarowa/domain/member/dto/response/MemberListResponseDTO.java
- src/main/java/com/ss/hanarowa/domain/member/service/impl/AdminMemberServiceImpl.java
- src/main/java/com/ss/hanarowa/global/config/CustomSecurityConfig.java
> Fix : admin member list
